# Generated by Django 4.0.2 on 2022-02-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='profiles/icon_profile_default_new.png', null=True, upload_to='profiles/'),
        ),
    ]
