# Generated by Django 4.0.2 on 2022-02-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='profiles/default_new.jpg', null=True, upload_to='profiles/'),
        ),
    ]
