# Generated by Django 4.0.1 on 2022-02-13 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_options_review_owner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-vote_ration', '-vote_total', 'title']},
        ),
    ]
